---
networks:
  dvwa:
    name: dvwa

volumes:
  dvwa:

services:
  dvwa-app:
    image: ghcr.io/digininja/dvwa:latest
    restart: always
    environment:
      - DB_SERVER=dvwa-db
    ports:
      - 4280:80
    depends_on:
      - dvwa-db
    networks:
      - dvwa

  dvwa-db:
    image: docker.io/library/mariadb:10
    environment:
      - MYSQL_ROOT_PASSWORD=dvwa
      - MYSQL_DATABASE=dvwa
      - MYSQL_USER=dvwa
      - MYSQL_PASSWORD=p@ssw0rd
    volumes:
      - dvwa:/var/lib/mysql
    networks:
      - dvwa
    restart: unless-stopped

  pings:
    build:
      context: script_atk/
    container_name: pings
    depends_on:
      - dvwa-app
    command: /bin/bash /scripts/ping.sh dvwa-app
    networks:
      - dvwa

  portscanning:
    build:
      context: script_atk/
    container_name: portscanning
    depends_on:
      - dvwa-app
    command: /bin/bash /scripts/portscanning.sh dvwa-app
    networks:
      - dvwa

  bruteforce:
    build:
      context: script_atk/
    container_name: bruteforce
    depends_on:
      - dvwa-app
    command: /bin/bash /scripts/bruteforce.sh dvwa-app username.txt rockyou.txt
    networks:
      - dvwa

  webcrawling:
    build:
      context: script_atk/
    container_name: webcrawling
    depends_on:
      - dvwa-app
    command: /bin/bash /scripts/webcrawling.sh dvwa-app common.txt
    networks:
      - dvwa

  glouton:
    build:
      context: glouton/
