---
version: "3"

env:
  COMPOSE_ALL_FILES: -f docker-compose.yml -f docker-compose.logs.yml -f docker-compose.atk.yml
  COMPOSE_LOGGING: -f docker-compose.yml -f docker-compose.logs.yml
  COMPOSE_ATTACK: -f docker-compose.yml -f docker-compose.atk.yml
  ELK_SERVICES: elasticsearch logstash kibana apm-server
  ELK_LOG_COLLECTION: filebeat
  ATTACK_SERVICES: dvwa-app dvwa-db pings

tasks:
  keystore:
    silent: true
    internal: true
    cmds:
      - docker compose -f docker-compose.setup.yml run --rm keystore
  certs:
    silent: true
    internal: true
    cmds:
      - docker compose -f docker-compose.setup.yml run --rm certs

  setup:
    silent: true
    cmds:
      - task: keystore
      - task: certs

  elk:
    silent: true
    cmds:
      - docker compose up -d --build

  monitoring:
    silent: true
    cmds:
      - docker compose ${COMPOSE_LOGGING} up -d --build ${ELK_LOG_COLLECTION}

  windows:
    silent: true
    platforms: [windows]
    cmds:
      - wsl -d docker-desktop sysctl -w vm.max_map_count=262144

  attack:
    silent: true
    cmds:
      - docker compose ${COMPOSE_ATTACK} up -d --build ${ATTACK_SERVICES}

  up:
    silent: true
    cmds:
      - task: windows
      - task: elk
      - task: monitoring
      - >
        echo "Visit Kibana: https://localhost:5601"

  down:
    silent: true
    cmds:
      - docker compose ${COMPOSE_ALL_FILES} down
